version: 2

project_name: sbom-validator

builds:
  - id: sbom-validator-example
    main: ./example
    binary: sbom-validator
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - ids:
      - sbom-validator-example
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256
