FROM golang:1.25.7-alpine3.23@sha256:f6751d823c26342f9506c03797d2527668d095b0a15f1862cddb4d927a7a4ced
ARG VERSION=not_versioned
ARG CYCLONEDX_GOLANG_VERSION=v1.9.0
RUN mkdir /app && mkdir /sbom
COPY . /app/
WORKDIR /app
RUN go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@${CYCLONEDX_GOLANG_VERSION} \
    && cyclonedx-gomod version \
    && cyclonedx-gomod mod -type library -json -output bom.json . \
    && cp /app/bom.json /sbom/sbom.json
