name: GoReleaser

on:
  push:
    tags:
    - 'v*'

permissions: { }

jobs:
  goreleaser:
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v4.2.2
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # tag=v5.2.0
      with:
        go-version: "1.21"
        check-latest: true
    - name: Generate SBOM
      uses: CycloneDX/gh-gomod-generate-sbom@v2
      with:
        version: v1
        args: mod -licenses -json -output-version 1.6 -output sbom-validator.${{ github.ref_name }}.cdx.json
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # tag=v6.1.0
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Archive SBOM
      uses: actions/upload-artifact@v4
      with:
        name: SBOM
        path: sbom-validator.${{ github.ref_name }}.cdx.json
