name: Go Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions: read-all

jobs:
  lint:
    uses: shiftleftcyber/supply-chain-workflows/.github/workflows/go-lint.yml@v1
    with:
      go-version-file: go.mod
      golangci-lint-version: v2.8.0
      working-directory: .
