name: Release Workflow

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  actions: read
  attestations: write
  contents: write
  id-token: write

jobs:
  source-sbom:
    uses: shiftleftcyber/supply-chain-workflows/.github/workflows/source-sbom-go.yml@v1
    with:
      artifact-name: signed-release-sbom
      fail-on-vulnerabilities: true
      file-prefix: sbom-validator-${{ github.ref_name }}
      go-version-file: go.mod
      secure-sbom-signing-key-id: ${{ vars.SECURE_SBOM_SIGNING_KEY_ID }}
      source-directory: .
    secrets:
      secure-sbom-api-key: ${{ secrets.SECURE_SBOM_API_KEY }}

  release:
    needs: source-sbom
    uses: shiftleftcyber/supply-chain-workflows/.github/workflows/release-go.yml@v1
    with:
      config: .goreleaser.yml
      evidence-artifact-name: ${{ needs.source-sbom.outputs.artifact-name }}
      evidence-file: ${{ needs.source-sbom.outputs.signed-sbom-file }}
      go-version-file: go.mod
      update-major-tag: true
      working-directory: .

  publish-interlynk:
    needs: source-sbom
    uses: shiftleftcyber/supply-chain-workflows/.github/workflows/publish-sbom-interlynk.yml@v1
    with:
      artifact-name: ${{ needs.source-sbom.outputs.artifact-name }}
      environment: Production
      product: sbom-validator
      sbom-file: ${{ needs.source-sbom.outputs.signed-sbom-file }}
    secrets:
      interlynk-security-token: ${{ secrets.INTERLYNK_TOKEN }}
