name: Go Security

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "30 12 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  security:
    uses: shiftleftcyber/supply-chain-workflows/.github/workflows/security-go.yml@c4b3a0e6e31f5b47d5f792da6b39eee0f058c9a9
    with:
      go-version-file: go.mod
      working-directory: .
