name: Go Security

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "30 12 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  security:
    uses: shiftleftcyber/supply-chain-workflows/.github/workflows/security-go.yml@24a5f2c9627962cf146079196bbf2a42138324a6
    with:
      go-version-file: go.mod
      working-directory: .
